---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache. (Deb)
      ansible.builtin.apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install github3.py python package.
      ansible.builtin.pip:
        name: github3.py

  roles:
    - role: iancleary.gh
      variable:
        gh_version: 2.25.1
